### ISSUE TITLE
Temp and Humidity

### ISSUE THREAD

**Issue by quinntj** [chaunceygardiner/weewx-airlink#2]
Hello! 
Does this driver store the reported temp and humidity in the DB somewhere? I'd like to graph it along with my station measurements. (one is on the roof, the other about 6' off the ground)

Thanks!

**Comment by chaunceygardiner** [comment]
Short answer, it does not save them.

On a tangent, the humidity and temperature are required for the EPA correction.  As such, in the us_epa_correction branch of this repository, I am computing the EPA corrected PM2.5 concentration and storing that int the PM2_5 field.  That branch will eventually become weewx-airlink v. 1.0.
