### ISSUE TITLE
Added Wet Bulb reading to database (Not an issue)

### ISSUE THREAD

**Issue by Stormtracker017** [chaunceygardiner/weewx-airlink#3]
I modified airlink.py to add the wet bulb measurement to the weewx database.  Hopefully this is the correct way of adding the measurement.

Added the following:

Line 79: weewx.units.obs_group_dict['wet_bulb'] = 'group_temperature'
Line 103: wet_bulb : float
Line 142: wet_bulb  = record['wet_bulb'],
Line 463:  # Add wetbulb    
                if cfg.concentrations.wet_bulb is not None:
                    packet['wet_bulb']      = cfg.concentrations.wet_bulb
                elif cfg.concentrations.wet_bulb_last is not None:
                    packet['wet_bulb']      = cfg.concentrations.wet_bulb_last

Expanded the database to include Wet Bulb.

**Comment by chaunceygardiner** [comment]
Acknowledged.
