### ISSUE TITLE
Upload AQI to Weather Underground

### ISSUE THREAD

**Issue by jshatch** [chaunceygardiner/weewx-airlink#6]
Are you planning a way for us to upload the AQI from our Airlink units to WU like the PurpleAir units do, or is that reserved exclusively for PurpleAir?  I asked WU Support if it's allowed and they haven't said anything yet.

**Comment by chaunceygardiner** [comment]
Hi,

If we could upload to WU, this extension may not be the best place to do it.  It would be more straightforward to include AQI with the rest of the WeeWX readings in the existing WU upload code.  I’ll close this issue; but if you hear back from WU that it is possible to upload AQI to WU, please reopen the issue and I’ll look at supporting it.  (Although that may be with a pull request to WeeWX proper or a separate service.)
