### ISSUE TITLE
Support multiple sensors with separate archive data

### ISSUE THREAD

**Issue by trodemaster** [chaunceygardiner/weewx-airlink#7]
We have an Airlink inside and outside and would like to track the data independently. I see that the current implementation just logs whichever configured sensor responds first. 

Ideally, you could extend the weedb with `archive_day_extra_pm2_51` or similar and have the weewx-airlink archive that data separately. 

Thanks,
Blake

**Comment by chaunceygardiner** [comment]
A design goal of the plugin was to not require modifying the database.  If that were not the goal, I would be saving everything from the sensor.  I may explore this for both the purpleair and the airlink, but if and when I do, it will be a separate plugin.

**Comment by jshatch** [comment]
Out of curiosity, would you consider writing all sensor data to a separate table (or tables in the case of multiple sensors) and run calculations from that? Or does that fall under modifying too much?

**Comment by chaunceygardiner** [comment]
The easiest thing for you to do would be to run a second copy of weewx.  You could just use the simulator driver for the second copy and specify your indoor airlink sensor.  You can then include the indoor airlink readings in your reports from your main instance of weewx.

You can get help specifying the bindings to your alternate weewx instance on weewx-user.
